cointhon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('investify/', include("main.urls"), name="main")

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from unicodedata import name
from xml.etree.ElementInclude import include
from django.urls import path
from .views import home, about, register, login_view, profile, transfer, transfer_confirm, transaction_history, history, logout_view

app_name = "main"

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('sign-up/', register, name="register"),
    path('login/', login_view, name="login"),
    path('dashboard/<int:pk>/home', profile, name="profile"),
    path('transfer/', transfer, name="transfer"),
    path('transfer/confirmation/<ref>', transfer_confirm, name="confirmation"),
    path('<us>/transaction_history', transaction_history, name="history"),
    path('transaction/<ref>', history, name="details"),
    path('logout/', logout_view, name="logout")
]

templates/succesful.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <style type="text/css">
        body {
            background: #f2f2f2;
        }
        
        .payment {
            border: 1px solid #f2f2f2;
            height: 280px;
            border-radius: 20px;
            background: #fff;
        }
        
        .payment_header {
            background: rgba(255, 102, 0, 1);
            padding: 20px;
            border-radius: 20px 20px 0px 0px;
        }
        
        .check {
            margin: 0px auto;
            width: 50px;
            height: 50px;
            border-radius: 100%;
            background: #fff;
            text-align: center;
        }
        
        .check i {
            vertical-align: middle;
            line-height: 50px;
            font-size: 30px;
        }
        
        .content {
            text-align: center;
        }
        
        .content h1 {
            font-size: 25px;
            padding-top: 25px;
        }
        
        .content a {
            width: 200px;
            height: 35px;
            color: #fff;
            border-radius: 30px;
            padding: 5px 10px;
            background: rgba(255, 102, 0, 1);
            transition: all ease-in-out 0.3s;
        }
        
        .content a:hover {
            text-decoration: none;
            background: #000;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto mt-5">
                <div class="payment">
                    <div class="payment_header">
                        <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
                    </div>
                    <div class="content">
                        <h1>Payment Success !</h1>
                        <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. </p>
                        <a href="{% url 'main:home'%}">Go to Home</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>